2025-01-10 04:14:51,850 - INFO - Starting training pipeline
2025-01-10 04:14:51,850 - INFO - Using device: cpu
2025-01-10 04:14:51,850 - INFO - Loading data...
2025-01-10 04:14:54,001 - INFO - Data loaded and cleaned. Shape: (603, 4351)
2025-01-10 04:14:54,162 - INFO - Train set size: 482, Validation set size: 121
2025-01-10 04:15:14,242 - INFO - Data loaders created
2025-01-10 04:15:14,367 - INFO - Model initialized
2025-01-10 04:15:14,367 - INFO - Starting model training...
2025-01-10 04:18:38,519 - ERROR - Error during training: index_select(): Index is supposed to be a vector
Traceback (most recent call last):
  File "C:\Users\jegol\CryptoProjects\BOTGITREPO\CRYPTOBOTS\NNbot\TimeToPeak\models\time_to_peak_model.py", line 477, in main
    model, training_stats, best_val_loss = train_model(
  File "C:\Users\jegol\CryptoProjects\BOTGITREPO\CRYPTOBOTS\NNbot\TimeToPeak\models\time_to_peak_model.py", line 292, in train_model
    mean, log_var = model(batch)
  File "C:\Users\jegol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\jegol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\jegol\CryptoProjects\BOTGITREPO\CRYPTOBOTS\NNbot\TimeToPeak\models\time_to_peak_model.py", line 157, in forward
    processed = self.granularity_processors[granularity](features, lengths)
  File "C:\Users\jegol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\jegol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\jegol\CryptoProjects\BOTGITREPO\CRYPTOBOTS\NNbot\TimeToPeak\models\time_to_peak_model.py", line 103, in forward
    packed_x = nn.utils.rnn.pack_padded_sequence(
  File "C:\Users\jegol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\utils\rnn.py", line 336, in pack_padded_sequence
    input = input.index_select(batch_dim, sorted_indices)
IndexError: index_select(): Index is supposed to be a vector
